EMAIL_KEY      = 'SOME LONG RANDOM KEY'
EMAIL_SALT    = 'ANOTHER LONG RANDOM KEY'

POST_ADDR = "YOUR MAILGUN POST ADDRESS"
MAILGUN_API = "YOUR API KEY"

ALERTS_EMAIL = "Alerts <alerts@mailer.openorders.ca>"